# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Req2.xdc

# Block Designs: bd/Req2/Req2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Req2 || ORIG_REF_NAME==Req2} -quiet] -quiet

# IP: bd/Req2/ip/Req2_Req2_7seg_0_0/Req2_Req2_7seg_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Req2_Req2_7seg_0_0 || ORIG_REF_NAME==Req2_Req2_7seg_0_0} -quiet] -quiet

# IP: bd/Req2/ip/Req2_Req2Decoder_0_0/Req2_Req2Decoder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Req2_Req2Decoder_0_0 || ORIG_REF_NAME==Req2_Req2Decoder_0_0} -quiet] -quiet

# IP: bd/Req2/ip/Req2_Req2DispCounter_0_0/Req2_Req2DispCounter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Req2_Req2DispCounter_0_0 || ORIG_REF_NAME==Req2_Req2DispCounter_0_0} -quiet] -quiet

# IP: bd/Req2/ip/Req2_Req2Mux_0_0/Req2_Req2Mux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Req2_Req2Mux_0_0 || ORIG_REF_NAME==Req2_Req2Mux_0_0} -quiet] -quiet

# IP: bd/Req2/ip/Req2_Req2Div_0_0/Req2_Req2Div_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Req2_Req2Div_0_0 || ORIG_REF_NAME==Req2_Req2Div_0_0} -quiet] -quiet

# IP: bd/Req2/ip/Req2_Req2FSM_0_0/Req2_Req2FSM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Req2_Req2FSM_0_0 || ORIG_REF_NAME==Req2_Req2FSM_0_0} -quiet] -quiet

# IP: bd/Req2/ip/Req2_Req2Counter_0_0/Req2_Req2Counter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Req2_Req2Counter_0_0 || ORIG_REF_NAME==Req2_Req2Counter_0_0} -quiet] -quiet

# IP: bd/Req2/ip/Req2_Req2Counter_0_1/Req2_Req2Counter_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Req2_Req2Counter_0_1 || ORIG_REF_NAME==Req2_Req2Counter_0_1} -quiet] -quiet

# IP: bd/Req2/ip/Req2_Req2Counter_0_2/Req2_Req2Counter_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Req2_Req2Counter_0_2 || ORIG_REF_NAME==Req2_Req2Counter_0_2} -quiet] -quiet

# IP: bd/Req2/ip/Req2_Req2Counter_0_3/Req2_Req2Counter_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Req2_Req2Counter_0_3 || ORIG_REF_NAME==Req2_Req2Counter_0_3} -quiet] -quiet

# IP: bd/Req2/ip/Req2_util_vector_logic_0_0/Req2_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Req2_util_vector_logic_0_0 || ORIG_REF_NAME==Req2_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/Req2/ip/Req2_util_vector_logic_0_1/Req2_util_vector_logic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Req2_util_vector_logic_0_1 || ORIG_REF_NAME==Req2_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/Req2/ip/Req2_util_vector_logic_0_2/Req2_util_vector_logic_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Req2_util_vector_logic_0_2 || ORIG_REF_NAME==Req2_util_vector_logic_0_2} -quiet] -quiet

# XDC: c:/Users/denis/Desktop/Proj11/Proj11.gen/sources_1/bd/Req2/Req2_ooc.xdc
